python -u main.py \
--gpus 0,1 \
--n_GPUs 2 \
--model RCAN_bireal7 \
--save rcan_bireal7 \
--res_scale 1 \
--binary_mode binary \
--dir_data /home/zhangxiao/langzhiqiang/sr_data/ \
--epochs 300 \
--decay 200 \
--lr 2e-4 \
--data_test Set5+Set14+Urban100 \
--scale 4 \
--n_resgroups 10 \
--n_resblocks 5 \
--n_feats 64 \
--res_scale 1 \
--n_colors 1
